"""default subscription

Revision ID: 17c25419fb92
Revises: c7270f8e02d9
Create Date: 2024-10-20 01:29:13.214369

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17c25419fb92'
down_revision: Union[str, None] = 'c7270f8e02d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'size',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='files_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='files_pkey'),
    )
    op.create_table(
        'subscriptions',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default=sa.text("nextval('subscriptions_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['subscription_id'], ['subscriptions.id'], name='users_subscription_id_fkey'
        ),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
